window.CITY = {
  name: "Los Angeles",
  crimeSource: "violent crime the Los Angeles Police Department recorded outdoors",
  crimeCats: "Los Angeles Police Department incidents from January 2023 through December 2025 in the assault, battery, robbery and homicide categories (the counterparts of New York City's felony assault, misdemeanor assault, robbery and murder), drawn from the department's old records system through early 2024 and its new one after that",
  outdoorDef: "Only incidents in public outdoor places count: streets, sidewalks, alleys, freeways, bridges and underpasses, parks, beaches, the river bed, vacant lots, parking lots and garages, bus stops and terminals, construction sites, cemeteries and encampments, plus attacks inside cars, taxis and food trucks. Homes (including porches, yards, patios and driveways), businesses, gas stations, schools, hospitals, police stations and Metro trains, buses and stations are excluded.",
  lightingDesc: "Calibrated nighttime radiance (nW/cm²/sr) from NASA's VIIRS Black Marble annual composites (VNP46A4) for 2023, 2024 and 2025, averaged with equal weight. Each 500-meter square takes the area-weighted mean of the satellite pixels that overlap it.",
  lightingShort: "VIIRS Black Marble annual radiance, 2023–2025 average",
  gridName: "a 500-meter grid",
  gridLimit: "each 500-meter square averages several blocks",
  geocodeCaveat: "Los Angeles places each crime at the nearest hundred block, not the exact address.",
  denseArea: "Downtown and Hollywood",
  bounds: [[33.70, -118.67], [34.34, -118.15]],
  center: [34.02, -118.41],
  zoom: 10.5,
  minZoom: 9,
  geoBox: { s: 33.68, n: 34.36, w: -118.69, e: -118.13 },
  staleNote: "The city's public 311 file ends July 4, 2025, so the streetlight complaint hotspots cover January 2023 to July 2025.",
};
