window.CITY = {
  name: "Los Angeles",
  crimeSource: "violent crime the Los Angeles Police Department recorded",
  crimeCats: "Los Angeles Police Department incidents in the assault, battery, robbery and homicide categories, from its old records system through early 2024 and its new one after that",
  outdoorDef: "Only incidents in public outdoor places count: streets, sidewalks, alleys, freeways, bridges and underpasses, parks, beaches, the river bed, vacant lots, parking lots and garages, bus stops and terminals, construction sites, cemeteries and encampments, plus attacks inside cars, taxis and food trucks. Homes (including porches, yards, patios and driveways), businesses, gas stations, schools, hospitals, police stations and Metro trains, buses and stations are excluded.",
  outageTypes: "the single- and multiple-streetlight MyLA311 requests",
  geocodeCaveat: "Los Angeles geocodes each crime to the nearest hundred block, not the exact address, to protect privacy &mdash; so crime points are snapped to block midpoints.",
  denseArea: "Downtown and Hollywood",
  bounds: [[33.70, -118.67], [34.34, -118.15]],
  center: [34.02, -118.41],
  zoom: 10.5,
  minZoom: 9,
  geoBox: { s: 33.68, n: 34.36, w: -118.69, e: -118.13 },
  staleNote: "Crime covers January 2023 through December 2025. The city's public 311 file ends July 4, 2025, so the streetlight complaints cover January 2023 to July 2025.",
};
