window.CITY = {
  name: "Chicago",
  crimeSource: "violent crime Chicago police recorded outdoors",
  crimeCats: "Chicago Police incidents from January 2023 through December 2025 in the assault, battery, robbery and homicide categories (the counterparts of New York City's felony assault, misdemeanor assault, robbery and murder)",
  outdoorDef: "Only incidents in public outdoor places count: streets, sidewalks, alleys, highways, bridges, parks, forest preserves, the lakefront, vacant lots, parking lots and garages, Chicago Housing Authority grounds, bus stops, construction sites and cemeteries, plus attacks inside cars, taxis and ride-share vehicles. Homes (including porches, yards and driveways), businesses, gas stations, schools, hospitals, police stations and Chicago Transit Authority trains, buses, stations and platforms are excluded.",
  lightingDesc: "Calibrated nighttime radiance (nW/cm²/sr) from NASA's VIIRS Black Marble annual composites (VNP46A4) for 2023, 2024 and 2025, averaged with equal weight. Each 500-meter square takes the area-weighted mean of the satellite pixels that overlap it.",
  lightingShort: "VIIRS Black Marble annual radiance, 2023–2025 average",
  gridName: "a 500-meter grid",
  gridLimit: "each 500-meter square averages several blocks",
  geocodeCaveat: "Chicago publishes each crime at the block level, not the exact address.",
  denseArea: "the Loop",
  bounds: [[41.62, -87.95], [42.05, -87.50]],
  center: [41.84, -87.68],
  zoom: 11,
  minZoom: 9,
  geoBox: { s: 41.60, n: 42.07, w: -87.97, e: -87.48 },
  staleNote: "",
};
